version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - cyclop
    - depguard
    - dupl
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - godot
    - gocyclo
    - ireturn
    - lll
    - maintidx
    - mnd
    - nlreturn
    - revive
    - varnamelen
    - wrapcheck
    - wsl
