// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
	"time"
)

type JobApplication struct {
	AppliedAt      time.Time
	UpdatedAt      time.Time
	CreatedAt      time.Time
	Company        string
	Title          string
	Status         string
	Url            string
	ID             int64
	UserID         int64
	Archived       int64
	SalaryMin      sql.NullInt64
	SalaryMax      sql.NullInt64
	SalaryCurrency sql.NullString
}

type JobApplicationNote struct {
	CreatedAt        time.Time
	Note             string
	ID               int64
	JobApplicationID int64
}

type JobApplicationStat struct {
	CreatedAt             time.Time
	UpdatedAt             time.Time
	AverageTimeToHearBack int64
	TotalApplications     int64
	TotalCompanies        int64
	TotalAccepted         int64
	TotalApplied          int64
	TotalCanceled         int64
	TotalDeclined         int64
	TotalInterviewing     int64
	TotalOffers           int64
	TotalRejected         int64
	TotalWatching         int64
	TotalWidthdrawn       int64
	UserID                int64
	ID                    int64
}

type JobApplicationStatusHistory struct {
	CreatedAt        time.Time
	Status           string
	ID               int64
	JobApplicationID int64
}

type Session struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	Token     string
	UserAgent string
	ID        int64
	UserID    int64
	IpAddress string
}

type User struct {
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Email            string
	Password         string
	ID               int64
	InitialIpAddress string
}
