root = "../.."
testdata_dir = "testdata"
tmp_dir = "./cmd/ui/tmp"

[build]
  args_bin = []
  bin = "./tmp/ui"
  cmd = "CGO_ENABLED=1 go build -o ./tmp/ui ."
  delay = 1000
  exclude_dir = ["ui/assets/css", "tmp", "cmd/ui/tmp", "vendor", "testdata", "cmd/mcp", "mcp", "bin", "ui/e2e", "ui/goreleaser-dist"]
  exclude_file = ["ui/components/**/*.go", "internal/db/queries/*.go", "ui/dist/assets/css/output@dev.css"]
  exclude_regex = ["_test.go",".*_templ.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = "LOG_LEVEL=debug go tool godotenv ../../.env ./tmp/ui"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "css", "sql"]
  include_file = []
  kill_delay = "5s"
  log = "build-errors.log"
  poll = false
  poll_interval = 500
  post_cmd = [
    # https://github.com/cosmtrek/air/issues/534
    "lsof -i :8080 -sTCP:LISTEN | sed 1d | awk '{print $2}' | xargs kill -9",
  ]
  pre_cmd = [
    "lsof -i :8080 -sTCP:LISTEN | sed 1d | awk '{print $2}' | xargs kill -9",
    "cd ../.. && go tool templ generate -path ./ui/components",
    "cd ../.. && go tool go-tw -i ./ui/styles/input.css -o ./ui/dist/assets/css/output@dev.css",
    "cd ../.. && go tool sqlc generate",
    "cd ../.. && go tool migrate -source file://./internal/db/migrations -database sqlite3://$(go tool godotenv printenv DB_URL)"
  ]
  rerun = true
  rerun_delay = 500
  send_interrupt = true 
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[proxy]
  enabled = true
  proxy_port = 8090
  app_port = 8080
