version: 2

project_name: pathwise-ui
dist: goreleaser-dist

before:
  hooks:
    - go mod download
    - go tool sqlc generate
    - go tool templ generate -path ./ui/components
    - go tool go-tw -i ./ui/styles/input.css -o ./ui/dist/assets/css/output@{{ replace .Version "ui/" "" }}.css --minify

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/ui
    binary: pathwise-ui
    ldflags:
      - -s -w -X github.com/Piszmog/pathwise/ui/version.Value={{ replace .Version "ui/" "" }}
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ['zip']

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
