name: CI MCP
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mcp/**'
      - 'cmd/mcp/**'
      - 'internal/**'
      - 'sqlc.yml'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches:
      - main
    paths:
      - 'mcp/**'
      - 'cmd/mcp/**'
      - 'internal/**'
      - 'sqlc.yml'
      - 'go.mod'
      - 'go.sum'
jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
      - run: go mod download
      - run: go tool sqlc generate
      - run: go test ./mcp/tool/... -tags=integration -v
  release-dryrun:
    name: Release Dry Run
    runs-on: ubuntu-latest
    needs: [integration]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: Run MCP GoReleaser
        run: |
          docker run \
            --rm \
            -v $PWD:/go/src/github.com/user/repo \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /go/src/github.com/user/repo \
            -e GITHUB_TOKEN \
            ghcr.io/goreleaser/goreleaser-cross:latest \
            release --clean --snapshot --skip=publish --config cmd/mcp/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker-publish:
    name: Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - integration
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/piszmog/pathwise
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: cmd/mcp/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
