name: CI UI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ui/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ui/**'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
      - run: go mod download
      - run: go tool templ generate -path ./components
      - run: go tool sqlc vet
      - run: go tool sqlc generate
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
      - run: go mod download
      - run: go tool templ generate -path ./components
      - run: go tool sqlc generate
      - name: Test
        run: go test -race ./...
  e2e:
    name: End-to-End
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
      - run: go mod download
      - run: go tool templ generate -path ./components
      - run: go tool sqlc generate
      - run: go test ./... -tags=e2e
  docker-publish:
    name: Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    permissions:
      contents: read
      packages: write
    needs:
      - lint
      - test
      - e2e
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/piszmog/pathwise
      - uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
