name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false
      - run: go mod download
      - run: go tool templ generate -path ./ui/components
      - run: go tool sqlc vet
      - run: go tool sqlc generate
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false
      - run: go mod download
      - run: go tool templ generate -path ./ui/components
      - run: go tool sqlc generate
      - run: go test -race ./...
