name: CI
on:
  push:
    branches:
      - main
    pull_request:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      - run: go mod download
      - run: go install github.com/a-h/templ/cmd/templ@v0.2.648
      - run: templ generate -path ./components
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      - run: go mod download
      - run: go install github.com/a-h/templ/cmd/templ@v0.2.648
      - run: templ generate -path ./components
      - name: Test
        run: go test -race ./...
