name: CI
on:
  push:
    branches:
      - main
    pull_request:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - run: go mod download
      - run: go install github.com/a-h/templ/cmd/templ@v0.2.648
      - run: templ generate -path ./components
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          skip-pkg-cache: true
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - run: go mod download
      - run: go install github.com/a-h/templ/cmd/templ@v0.2.648
      - run: templ generate -path ./components
      - name: Test
        run: go test -race ./...
  docker-publish:
    name: Publish Docker
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/piszmog/pathwise
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
