name: Release
on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Version increment type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch
permissions:
  contents: write
jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest release
        id: latest_release
        run: |
          LATEST_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" = "null" ]; then
            LATEST_TAG="v0.0.0"
          fi
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Calculate new version
        id: version
        run: |
          LATEST_TAG="${{ steps.latest_release.outputs.latest_tag }}"
          INCREMENT="${{ github.event.inputs.increment }}"
          # Remove 'v' prefix if present
          VERSION=${LATEST_TAG#v}
          # Split version into parts
          IFS='.' read -ra VERSION_PARTS <<< "$VERSION"
          MAJOR=${VERSION_PARTS[0]:-0}
          MINOR=${VERSION_PARTS[1]:-0}
          PATCH=${VERSION_PARTS[2]:-0}
          # Calculate new version based on increment type
          case $INCREMENT in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Calculated new version: $NEW_VERSION (from $LATEST_TAG using $INCREMENT increment)"
      - name: Announce new version
        run: |
          echo "::notice title=New Release Version::Releasing ${{ steps.version.outputs.new_version }} (increment: ${{ github.event.inputs.increment }})"
  tag:
    name: Tag
    runs-on: ubuntu-latest
    needs: [calculate-version]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Tag
        uses: piszmog/create-tag@v1
        with:
          version: ${{ needs.calculate-version.outputs.new_version }}
          message: ${{ needs.calculate-version.outputs.new_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [tag]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: Run UI GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean --config cmd/ui/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload UI Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: pathwise-ui_Linux_x86_64.tar.gz
          path: cmd/ui/goreleaser-dist/pathwise-ui_Linux_x86_64.tar.gz
          retention-days: 1
  publish:
    name: Publish UI Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [calculate-version, tag]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/piszmog/pathwise-ui
          tags: |
            type=raw,value=${{ needs.calculate-version.outputs.new_version }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: cmd/ui/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ needs.calculate-version.outputs.new_version }}
  deploy-gae-ui:
    name: Deploy UI to GAE
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: [calculate-version, tag]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: Get Version
        run: |
          VERSION="${{ needs.calculate-version.outputs.new_version }}"
          MODIFIED_VERSION="${VERSION//./-}"
          echo "VERSION_GCP=$MODIFIED_VERSION" >> $GITHUB_ENV
      - run: go mod download
      - run: go tool templ generate -path ./ui/components
      - run: go tool sqlc generate
      - run: go tool go-tw -i ./styles/input.css -o ./dist/assets/css/output@${{ needs.calculate-version.outputs.new_version }}.css --minify
      - name: Replace version
        run: sed -i 's/\${version}/'"$VERSION"'/' cmd/ui/app.yaml
        env:
          VERSION: ${{ needs.calculate-version.outputs.new_version }}
      - name: Replace token secret
        run: sed -i 's/\${secrets.DB_TOKEN}/'"$DB_TOKEN"'/' cmd/ui/app.yaml
        env:
          DB_TOKEN: ${{ secrets.DB_TOKEN }}
      # Create a service account in IAM with roles
      # App Engine Admin
      # Cloud Build Editor
      # Service Account User
      # Storage Admin
      # Artifact Registry Reader
      #
      # Create a Workload Identity Pool
      # Create a provider for pool
      # - ODIC
      # - issuer: https://token.actions.githubusercontent.com
      # - Default audience
      # - Attributes
      #   - google.subject: assertion.sub
      #   - attribute.actor: assertion.actor
      #   - attribute.repository: assertion.repository
      #
      # For service account, grant access to principal
      #   - New principals:  principalSet://iam.googleapis.com/projects/<project number>/locations/global/workloadIdentityPools/<pool id>/attribute.repository/<github owner>/<github repo>
      #   - Role: Workload Identity User
      #
      # Enable App Engine Admin API
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WORKLOAD_POOL_ID }}/providers/${{ secrets.GCP_WORKLOAD_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_NAME }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v2'
        with:
          version: ${{ env.VERSION_GCP }}
          deliverables: cmd/ui/app.yaml
  deploy-vm-ui:
    name: Deploy UI to VM
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pathwise-ui_Linux_x86_64.tar.gz
          path: ./artifacts

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Create systemd service file
        run: |
          cat > pathwise.service << 'EOF'
          [Unit]
          Description=Pathwise Job Application Tracker
          After=network.target

          [Service]
          Type=simple
          User=ubuntu
          WorkingDirectory=/home/ubuntu/apps/pathwise
          ExecStart=/home/ubuntu/apps/pathwise/pathwise-ui
          Restart=always
          RestartSec=5
          Environment=DB_TOKEN=${{ secrets.DB_TOKEN }}
          Environment=DB_URL=${{ secrets.DB_URL }}
          Environment=LOG_OUTPUT=/var/log/pathwise/pathwise.log
          Environment=PORT=8080

          [Install]
          WantedBy=multi-user.target
          EOF

      - name: Deploy to VM
        run: |
          # Copy artifact and service file to VM
          scp ./artifacts/pathwise-ui_Linux_x86_64.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/
          scp pathwise.service ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/

          # Extract and deploy on VM
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Stop existing service if it exists
            if sudo systemctl is-active --quiet pathwise; then
              sudo systemctl stop pathwise
            fi

            # Create app directory if it doesn't exist
            mkdir -p /home/ubuntu/apps/pathwise

            # Extract new version
            cd /tmp
            tar -xzf pathwise-ui_Linux_x86_64.tar.gz

            # Move binary to app directory
            mv pathwise-ui /home/ubuntu/apps/pathwise/
            chmod +x /home/ubuntu/apps/pathwise/pathwise-ui

            # Create log directory
            sudo mkdir -p /var/log/pathwise
            sudo chown ubuntu:ubuntu /var/log/pathwise

            # Install systemd service file
            sudo mv /tmp/pathwise.service /etc/systemd/system/
          EOF

          # Start service and health check
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Reload systemd and start service
            sudo systemctl daemon-reload
            sudo systemctl start pathwise
            sudo systemctl enable pathwise

            # Check status
            sudo systemctl status pathwise
            # Wait for service to start
            sleep 10
            # Health check
            if curl -f http://localhost:8080/health; then
              echo "✅ Health check passed - app is running"
            else
              echo "❌ Health check failed - app is not responding"
              exit 1
            fi
          EOF
      - name: Cleanup
        run: |
          rm -f ~/.ssh/id_rsa
